

// Movie Actions
export const MOVIES_REQUEST = 'MOVIES_REQUEST';
export const MOVIES_FAILURE = 'MOVIES_FAILURE';
export const GET_MOVIES = 'GET_MOVIES';
export const ADD_MOVIE = 'ADD_MOVIE';
export const DELETE_MOVIE = 'DELETE_MOVIE';
export const UPDATE_MOVIE = 'UPDATE_MOVIE';
export const SINGLE_MOVIE = 'SINGLE_MOVIE'


// Movie Show Actions
export const MOVIE_SHOWS_REQUEST = 'MOVIE_SHOWS_REQUEST';
export const MOVIE_SHOWS_FAILURE = 'MOVIE_SHOWS_FAILURE';
export const GET_MOVIE_SHOWS = 'GET_MOVIE_SHOWS';
export const ADD_MOVIE_SHOW = 'ADD_MOVIE_SHOW';
export const DELETE_MOVIE_SHOW = 'DELETE_MOVIE_SHOW';
export const UPDATE_MOVIE_SHOW = 'UPDATE_MOVIE_SHOW';
export const GET_SINGLE_MOVIE_SHOW = "GET_SINGLE_MOVIE_SHOW"
export const GET_MOVIE_SHOW_BOOKING ="GET_MOVIE_SHOW_BOOKING"
export const ADD_MOVIE_SHOW_BOOKING = "ADD_MOVIE_SHOW_BOOKING"
