export const AUTH_REQ= "AUTH_REQ"
export const AUTH_FAIL= "AUTH_FAIL"
export const SIGNUP_SUCCESS="SIGNUP_SUCCESS"
export const SIGNIN_SUCCESS="SIGNIN_SUCCESS"
export const UPDATE_SUCCESS="UPDATE_SUCCESS"
export const GET_SINGLE_USER= "GET_SINGLE_USER"


